// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbxxmqkf7X6zKSpQ5sKVKEP5Tr2goxPO0F21IAxMeIPyjK4ORmbJEaXST1NKhLPoXAGifw/exec";

